### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by vv-monsalve** [niteeshy/ar-one-sans#3]
Including information about the project:

- [x] Concept and design information
- [x] Images showcasing the font
- [x] Idelally information about the axes it uses

Readme referent cases could be: [Geologica](https://github.com/googlefonts/geologica) and  [Kablammo](https://github.com/Vectro-Type-Foundry/kablammo)

**Comment by niteeshy** [comment]
@vv-monsalve I have updated the font information in the readme file. Please have a look.

**Comment by vv-monsalve** [comment]
Thank you. I'll add the building instructions at the end of the process.

**Comment by niteeshy** [comment]
@vv-monsalve is there a way to remove this tag "generated from googlefonts/..." below the repository name?
<img width="366" alt="Screenshot 2023-04-21 at 11 43 22 AM" src="https://user-images.githubusercontent.com/26871553/233554928-f18c8b43-599a-4ecd-9f8b-1a15e4ad439a.png">

**Comment by vv-monsalve** [comment]
@niteeshy I'm afraid not.
