### ISSUE TITLE
Update the README.md file

### ISSUE THREAD

**Issue by vv-monsalve** [niteeshy/ar-one-sans#7]
Please update the readme file needs to get updated to the `ARRR` axis and the last design decisions.
E.g. clarifying the "optical weights" reference in the second paragraph and providing detail or examples next to sentences like 
> The letterforms are highly legible and have distinct shapes to avoid confusion between commonly misrecognized letters.

**Comment by niteeshy** [comment]
Updated the readme with all the required details.
